name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  linux:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Cache Conan packages
      uses: actions/cache@v3
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan2-${{ hashFiles('**/conanfile.txt') }}
    - uses: actions/checkout@v4
    - name: Install GCC
    #   uses: egor-tensin/setup-gcc@v1.3
    #   with:
    #     version: 14
    #     platform: x64
    #   with:
    #     python-version: '3.x'
    #     cache: 'pip'
      uses: Dup4/actions-setup-gcc@v1
      with:
        version: latest    - uses: actions/setup-python@v5
        cache: 'gcc'
    - run: git submodule update --init --recursive
    - run: pip install -r requirements.txt
    - run: conan profile detect || true
    - run: conan install packages --build=missing
    - run: meson setup build
      env:
        CC: gcc-14
        CXX: g++-14
        PKG_CONFIG_PATH: packages
    - run: meson test -C build
      env:
        COLUMNS: 128
        LINES: 48
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
